version: '3.7'

services:
  db:
    container_name: postgres
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stream-backend

  redis:
    container_name: redis
    image: redis:5.0
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379 # опционально; можно убрать, если порт наружу не нужен
    volumes:
      - redis_data:/data
    networks:
      - stream-backend

  redisinsight:
    container_name: redisinsight
    image: redis/redisinsight:latest
    restart: always
    ports:
      - 5540:5540 # UI будет доступен на http://localhost:8001
    depends_on:
      - redis
    volumes:
      - redisinsight_data:/db # сохранит историю подключений/настроек
    networks:
      - stream-backend

volumes:
  postgres_data:
  redis_data:
  redisinsight_data:

networks:
  stream-backend:
